// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountRoleSnapshot struct {
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	RoleName      string
	CanLogin      bool
	ValidUntil    pgtype.Timestamptz
	SampledActive bool
	CollectedAt   pgtype.Timestamptz
}

type AlertDelivery struct {
	EnvironmentID pgtype.UUID
	DedupKey      string
	DeliveredAt   pgtype.Timestamptz
}

type AnalysisRun struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	Status           string
	AnalyzerVersion  string
	FindingsProduced int32
	FindingsSaved    int32
	Error            pgtype.Text
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	RuleManifestHash string
}

type AuditAnnotation struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	AuditRunID    pgtype.UUID
	Kind          string
	Note          string
	Actor         string
	OccurredAt    pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type AuditBaseline struct {
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	TableName     string
	AuditRunID    pgtype.UUID
	SelectedAt    pgtype.Timestamptz
	SelectedBy    string
}

type AuditEnvironment struct {
	ID             pgtype.UUID
	Name           string
	Type           string
	DiscoveryMode  string
	Active         bool
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	ExpectsReplica bool
	Engine         string
}

type AuditRun struct {
	ID               pgtype.UUID
	EnvironmentID    pgtype.UUID
	Profile          string
	Status           string
	ServiceVersion   string
	CollectorVersion string
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	Warnings         []byte
	Errors           []byte
}

type AuditRunCoverage struct {
	ID            pgtype.UUID
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	CollectorName string
	DatabaseName  string
	Status        string
	RowsCollected int64
	Warning       pgtype.Text
	Error         pgtype.Text
	CollectedAt   pgtype.Timestamptz
}

type AuditSchedule struct {
	EnvironmentID pgtype.UUID
	Profile       string
	Enabled       bool
	NextRunAt     pgtype.Timestamptz
	LastStatus    pgtype.Text
	LastRunAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type AuditorOperationLog struct {
	ID            int64
	UserID        pgtype.UUID
	Username      string
	Action        string
	EnvironmentID pgtype.UUID
	ResourceID    pgtype.Text
	Result        string
	CreatedAt     pgtype.Timestamptz
}

type AuditorPrivilegeSnapshot struct {
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	RoleName      string
	IsSuperuser   bool
	CanCreateDb   bool
	CanCreateRole bool
	Replication   bool
	CanWrite      bool
	CheckFailed   bool
	CollectedAt   pgtype.Timestamptz
}

type AuditorSession struct {
	TokenHash []byte
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AuditorUser struct {
	ID           pgtype.UUID
	Username     string
	PasswordHash string
	Role         string
	Active       bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AuditorUserEnvironment struct {
	UserID        pgtype.UUID
	EnvironmentID pgtype.UUID
}

type BaselineComparison struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	TableName     string
	BaselineRunID pgtype.UUID
	AuditRunID    pgtype.UUID
	Status        string
	AddedTables   int32
	RemovedTables int32
	ChangedTables int32
	ComparedAt    pgtype.Timestamptz
}

type BaselineSelectionEvent struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	TableName     string
	PreviousRunID pgtype.UUID
	SelectedRunID pgtype.UUID
	SelectedBy    string
	SelectedAt    pgtype.Timestamptz
}

type ChunkSnapshot struct {
	ID                     pgtype.UUID
	AuditRunID             pgtype.UUID
	EnvironmentID          pgtype.UUID
	DatabaseName           string
	SchemaName             string
	HypertableName         string
	ChunkSchema            string
	ChunkName              string
	RangeStart             pgtype.Timestamptz
	RangeEnd               pgtype.Timestamptz
	RangeStartInteger      pgtype.Int8
	RangeEndInteger        pgtype.Int8
	IsCompressed           bool
	ChunkTablespace        pgtype.Text
	TotalSizeBytes         int64
	DataSizeBytes          int64
	IndexSizeBytes         int64
	CollectedAt            pgtype.Timestamptz
	BeforeCompressionBytes int64
	AfterCompressionBytes  int64
}

type ChunkVacuumSample struct {
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	DatabaseName     string
	HypertableSchema string
	HypertableName   string
	ChunkSchema      string
	ChunkName        string
	NDeadTup         int64
	NLiveTup         int64
	LastAutovacuum   pgtype.Timestamptz
	LastAnalyze      pgtype.Timestamptz
	CollectedAt      pgtype.Timestamptz
}

type CollectorRun struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	CollectorName    string
	CollectorVersion string
	Status           string
	QueryName        pgtype.Text
	StartedAt        pgtype.Timestamptz
	FinishedAt       pgtype.Timestamptz
	RowsCollected    int64
	Warning          pgtype.Text
	Error            pgtype.Text
}

type ColumnSnapshot struct {
	ID                 pgtype.UUID
	AuditRunID         pgtype.UUID
	EnvironmentID      pgtype.UUID
	DatabaseName       string
	SchemaName         string
	TableName          string
	ColumnName         string
	OrdinalPosition    int32
	DataType           string
	IsNullable         bool
	ColumnDefault      pgtype.Text
	IsGenerated        bool
	IdentityGeneration pgtype.Text
	CollationName      pgtype.Text
	CollectedAt        pgtype.Timestamptz
	ColumnComment      pgtype.Text
}

type ColumnStatSnapshot struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	DatabaseName     string
	SchemaName       string
	TableName        string
	ColumnName       string
	NullFraction     float64
	DistinctEstimate float64
	AverageWidth     int32
	Correlation      pgtype.Float8
	Source           string
	Quality          string
	CollectedAt      pgtype.Timestamptz
}

type ConstraintSnapshot struct {
	ID                   pgtype.UUID
	AuditRunID           pgtype.UUID
	EnvironmentID        pgtype.UUID
	DatabaseName         string
	SchemaName           string
	TableName            string
	ConstraintName       string
	ConstraintType       string
	ConstraintDefinition string
	IsValidated          bool
	IsDeferrable         bool
	IsDeferred           bool
	CollectedAt          pgtype.Timestamptz
	ConstrainedColumns   []string
	ReferencedSchemaName pgtype.Text
	ReferencedTableName  pgtype.Text
	ReferencedColumns    []string
	FkUpdateAction       pgtype.Text
	FkDeleteAction       pgtype.Text
	FkMatchType          pgtype.Text
}

type ContinuousAggregateSnapshot struct {
	ID                        pgtype.UUID
	AuditRunID                pgtype.UUID
	EnvironmentID             pgtype.UUID
	DatabaseName              string
	SchemaName                string
	ViewName                  string
	OwnerName                 pgtype.Text
	MaterializationSchema     pgtype.Text
	MaterializationHypertable pgtype.Text
	MaterializedOnly          bool
	CompressionEnabled        bool
	Finalized                 pgtype.Bool
	CollectedAt               pgtype.Timestamptz
	ViewDefinition            string
	LagInterval               string
	SourceHypertableSchema    pgtype.Text
	SourceHypertableName      pgtype.Text
	BucketInterval            pgtype.Text
}

type DatabaseSnapshot struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	DatabaseName     string
	OwnerName        pgtype.Text
	Encoding         pgtype.Text
	CollateName      pgtype.Text
	CtypeName        pgtype.Text
	AllowConnections bool
	IsTemplate       bool
	SizeBytes        int64
	ConnectionCount  int32
	CollectedAt      pgtype.Timestamptz
}

type DimensionSnapshot struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	DatabaseName     string
	SchemaName       string
	HypertableName   string
	DimensionNumber  int32
	ColumnName       string
	ColumnType       pgtype.Text
	DimensionType    pgtype.Text
	TimeInterval     pgtype.Text
	IntegerInterval  pgtype.Text
	IntegerNowFunc   pgtype.Text
	NumSlices        pgtype.Int4
	PartitioningFunc pgtype.Text
	CollectedAt      pgtype.Timestamptz
}

type ExtensionSnapshot struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	DatabaseName     string
	ExtensionName    string
	ExtensionVersion pgtype.Text
	SchemaName       pgtype.Text
	IsRelocatable    bool
	CollectedAt      pgtype.Timestamptz
}

type Finding struct {
	ID                pgtype.UUID
	EnvironmentID     pgtype.UUID
	AuditRunID        pgtype.UUID
	FindingType       string
	Severity          string
	Status            string
	Title             string
	Summary           string
	ObjectType        string
	ObjectKey         string
	DatabaseName      string
	SchemaName        string
	ObjectName        string
	Evidence          []byte
	DedupKey          string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	ResolvedAt        pgtype.Timestamptz
	Notes             pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	RuleID            string
	RuleVersion       string
	Category          string
	Confidence        pgtype.Numeric
	Impact            string
	Risk              string
	Recommendation    string
	Validation        string
	ReferenceUrls     []byte
	RuleParameters    []byte
	RecurrenceCount   int32
	SuppressionReason pgtype.Text
	SuppressedUntil   pgtype.Timestamptz
	SupersededBy      pgtype.UUID
	Assignee          string
	DueAt             pgtype.Timestamptz
}

type FindingAction struct {
	FindingID     pgtype.UUID
	Status        string
	OwnerName     string
	Justification string
	ResultNote    string
	UpdatedBy     string
	UpdatedAt     pgtype.Timestamptz
}

type FindingActionEvent struct {
	ID            int64
	FindingID     pgtype.UUID
	Status        string
	OwnerName     string
	Justification string
	ResultNote    string
	Actor         string
	RecordedAt    pgtype.Timestamptz
}

type FindingActionMeasurement struct {
	ID                 pgtype.UUID
	FindingID          pgtype.UUID
	BeforeRunID        pgtype.UUID
	AfterRunID         pgtype.UUID
	Metric             string
	BeforeValue        pgtype.Int8
	AfterValue         pgtype.Int8
	Comparable         bool
	ComparisonNote     string
	Hypothesis         string
	WindowNote         string
	RecordedBy         string
	RecordedAt         pgtype.Timestamptz
	WorkloadComparable bool
}

type FindingEvent struct {
	ID             pgtype.UUID
	FindingID      pgtype.UUID
	AuditRunID     pgtype.UUID
	EventType      string
	Reason         string
	Category       string
	Severity       string
	DatabaseName   string
	SchemaName     string
	ObjectName     string
	RuleVersion    string
	Title          string
	Summary        string
	Recommendation string
	FindingStatus  string
	Impact         string
	Risk           string
	Validation     string
	ReferenceUrls  []byte
	RuleParameters []byte
	Confidence     pgtype.Numeric
	Evidence       []byte
	RecordedAt     pgtype.Timestamptz
}

type FunctionSnapshot struct {
	ID                 pgtype.UUID
	AuditRunID         pgtype.UUID
	EnvironmentID      pgtype.UUID
	DatabaseName       string
	SchemaName         string
	FunctionName       string
	IdentityArguments  string
	OwnerName          pgtype.Text
	LanguageName       pgtype.Text
	IsSecurityDefiner  bool
	Volatility         pgtype.Text
	ParallelSafety     pgtype.Text
	Kind               pgtype.Text
	FunctionDefinition pgtype.Text
	CollectedAt        pgtype.Timestamptz
	Proconfig          string
	ReturnType         pgtype.Text
	SearchPathPinned   pgtype.Bool
	ExecuteRoles       []string
	Calls              pgtype.Int8
	TotalTimeMs        pgtype.Float8
	SelfTimeMs         pgtype.Float8
	StatsReset         pgtype.Timestamptz
	StatsObserved      pgtype.Bool
}

type GrantSnapshot struct {
	ID            pgtype.UUID
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	TableName     string
	Grantee       string
	Privileges    []string
	CollectedAt   pgtype.Timestamptz
}

type HypertableSnapshot struct {
	ID                 pgtype.UUID
	AuditRunID         pgtype.UUID
	EnvironmentID      pgtype.UUID
	DatabaseName       string
	SchemaName         string
	HypertableName     string
	OwnerName          pgtype.Text
	NumDimensions      int32
	NumChunks          int32
	CompressionEnabled bool
	IsDistributed      bool
	TotalSizeBytes     int64
	DataSizeBytes      int64
	IndexSizeBytes     int64
	CollectedAt        pgtype.Timestamptz
}

type IndexSnapshot struct {
	ID              pgtype.UUID
	AuditRunID      pgtype.UUID
	EnvironmentID   pgtype.UUID
	DatabaseName    string
	SchemaName      string
	TableName       string
	IndexName       string
	IndexDefinition string
	AccessMethod    pgtype.Text
	IsUnique        bool
	IsPrimary       bool
	SizeBytes       int64
	IdxScan         int64
	IdxTupRead      int64
	IdxTupFetch     int64
	CollectedAt     pgtype.Timestamptz
	StatsReset      pgtype.Timestamptz
	IsValid         bool
	IsReady         bool
	KeyColumns      []string
	Predicate       string
	IncludeColumns  []string
	UsageObserved   pgtype.Bool
}

type JobSnapshot struct {
	ID                   pgtype.UUID
	AuditRunID           pgtype.UUID
	EnvironmentID        pgtype.UUID
	DatabaseName         string
	JobID                int64
	ApplicationName      pgtype.Text
	ScheduleInterval     pgtype.Text
	MaxRuntime           pgtype.Text
	MaxRetries           int32
	RetryPeriod          pgtype.Text
	ProcSchema           pgtype.Text
	ProcName             pgtype.Text
	OwnerName            pgtype.Text
	Scheduled            bool
	FixedSchedule        bool
	ConfigJson           pgtype.Text
	NextStart            pgtype.Timestamptz
	InitialStart         pgtype.Timestamptz
	HypertableSchema     pgtype.Text
	HypertableName       pgtype.Text
	CheckSchema          pgtype.Text
	CheckName            pgtype.Text
	CollectedAt          pgtype.Timestamptz
	LastRunStatus        pgtype.Text
	TotalFailures        int64
	LastRunDuration      string
	MaxBackgroundWorkers int32
}

type ObjectDependencySnapshot struct {
	ID            pgtype.UUID
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SourceSchema  string
	SourceName    string
	SourceKind    string
	TargetSchema  string
	TargetName    string
	TargetKind    string
	CollectedAt   pgtype.Timestamptz
}

type ObjectMapping struct {
	ID                   pgtype.UUID
	SourceEnvironmentID  pgtype.UUID
	TargetEnvironmentID  pgtype.UUID
	SourceDatabase       string
	SourceSchema         string
	SourceObjectType     string
	SourceObjectName     string
	TargetDatabase       string
	TargetSchema         string
	TargetObjectType     string
	TargetObjectName     string
	RelationType         string
	Confidence           pgtype.Numeric
	Status               string
	SourceFingerprint    pgtype.Text
	TargetFingerprint    pgtype.Text
	FingerprintAlgorithm pgtype.Text
	Notes                pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type PolicySnapshot struct {
	ID               pgtype.UUID
	AuditRunID       pgtype.UUID
	EnvironmentID    pgtype.UUID
	DatabaseName     string
	JobID            int64
	PolicyType       string
	ProcSchema       pgtype.Text
	ProcName         pgtype.Text
	HypertableSchema pgtype.Text
	HypertableName   pgtype.Text
	ScheduleInterval pgtype.Text
	Scheduled        bool
	ConfigJson       pgtype.Text
	NextStart        pgtype.Timestamptz
	OwnerName        pgtype.Text
	CollectedAt      pgtype.Timestamptz
}

type QualityIssue struct {
	ID               pgtype.UUID
	ScanID           pgtype.UUID
	CheckKind        string
	ColumnName       string
	AffectedRows     int32
	SampledRows      int32
	Status           string
	OwnerName        string
	Justification    string
	ResultNote       string
	UpdatedBy        string
	UpdatedAt        pgtype.Timestamptz
	ValidationScanID pgtype.UUID
}

type QualityIssueEvent struct {
	ID               pgtype.UUID
	IssueID          pgtype.UUID
	PreviousStatus   string
	NewStatus        string
	Actor            string
	OwnerName        string
	Justification    string
	ResultNote       string
	RecordedAt       pgtype.Timestamptz
	ValidationScanID pgtype.UUID
}

type QualityScan struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	TableName     string
	SampleLimit   int32
	SampledRows   int32
	SampleMethod  string
	Actor         string
	CreatedAt     pgtype.Timestamptz
}

type RegressionAlert struct {
	ID             pgtype.UUID
	EnvironmentID  pgtype.UUID
	BaselineRunID  pgtype.UUID
	AuditRunID     pgtype.UUID
	Category       string
	Evidence       []byte
	Status         string
	Reason         string
	AcknowledgedBy string
	CreatedAt      pgtype.Timestamptz
	AcknowledgedAt pgtype.Timestamptz
}

type ReplicationSnapshot struct {
	AuditRunID         pgtype.UUID
	EnvironmentID      pgtype.UUID
	DatabaseName       string
	ReplicaCount       int32
	ApplyLagBytes      pgtype.Int8
	FlushLagBytes      pgtype.Int8
	WriteLagBytes      pgtype.Int8
	ReplayLagBytes     pgtype.Int8
	ArchiveFailedCount int64
	LastArchivedTime   pgtype.Timestamptz
	LastFailedTime     pgtype.Timestamptz
	PermissionOk       bool
	CollectedAt        pgtype.Timestamptz
}

type ReportArtifact struct {
	ReportJobID pgtype.UUID
	Content     []byte
	Sha256      string
	SizeBytes   int64
	Filename    string
	ContentType string
	CreatedAt   pgtype.Timestamptz
}

type ReportJob struct {
	ID             pgtype.UUID
	EnvironmentID  pgtype.UUID
	AuditRunID     pgtype.UUID
	ReportType     string
	Filters        []byte
	RequestedBy    string
	RuleVersion    string
	Status         string
	Attempts       int32
	IdempotencyKey string
	Error          pgtype.Text
	CreatedAt      pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	FinishedAt     pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

type RlsPolicySnapshot struct {
	ID            pgtype.UUID
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	TableName     string
	PolicyName    string
	Permissive    pgtype.Text
	Roles         []string
	Cmd           pgtype.Text
	Qual          pgtype.Text
	WithCheck     pgtype.Text
	CollectedAt   pgtype.Timestamptz
}

type RuleCatalog struct {
	RuleID            string
	RuleVersion       string
	Category          string
	Confidence        pgtype.Numeric
	Impact            string
	Risk              string
	Recommendation    string
	Validation        string
	ReferencesJson    []byte
	DefaultParameters []byte
	CreatedAt         pgtype.Timestamptz
}

type RulePolicy struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	SchemaName    string
	RuleID        string
	Enabled       bool
	Parameters    []byte
	UpdatedAt     pgtype.Timestamptz
}

type ScheduledReport struct {
	ID            pgtype.UUID
	EnvironmentID pgtype.UUID
	AuditRunID    pgtype.UUID
	ReportType    string
	Status        string
	CreatedAt     pgtype.Timestamptz
}

type SchemaSnapshot struct {
	ID                    pgtype.UUID
	AuditRunID            pgtype.UUID
	EnvironmentID         pgtype.UUID
	DatabaseName          string
	SchemaName            string
	OwnerName             pgtype.Text
	TableCount            int32
	ViewCount             int32
	MaterializedViewCount int32
	SequenceCount         int32
	FunctionCount         int32
	SizeBytes             int64
	CollectedAt           pgtype.Timestamptz
	Nspacl                string
}

type SequenceSnapshot struct {
	ID            pgtype.UUID
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SchemaName    string
	SequenceName  string
	DataType      pgtype.Text
	StartValue    pgtype.Numeric
	IncrementBy   pgtype.Numeric
	MaxValue      pgtype.Numeric
	MinValue      pgtype.Numeric
	Cycle         pgtype.Bool
	OwnedByTable  pgtype.Text
	OwnedByColumn pgtype.Text
	CollectedAt   pgtype.Timestamptz
	LastValue     pgtype.Numeric
}

type ServerSettingSnapshot struct {
	AuditRunID    pgtype.UUID
	EnvironmentID pgtype.UUID
	DatabaseName  string
	SettingName   string
	SettingValue  string
	CollectedAt   pgtype.Timestamptz
}

type SnapshotBackup struct {
	ID            int16
	LastSuccessAt pgtype.Timestamptz
	LastAttemptAt pgtype.Timestamptz
	LastStatus    string
	ArtifactPath  string
}

type TableSnapshot struct {
	ID                  pgtype.UUID
	AuditRunID          pgtype.UUID
	EnvironmentID       pgtype.UUID
	DatabaseName        string
	SchemaName          string
	TableName           string
	OwnerName           pgtype.Text
	Relkind             string
	DataSizeBytes       int64
	IndexSizeBytes      int64
	TotalSizeBytes      int64
	RowEstimate         int64
	NLiveTup            int64
	NDeadTup            int64
	NTupIns             int64
	NTupUpd             int64
	NTupDel             int64
	SeqScan             int64
	IdxScan             int64
	LastVacuum          pgtype.Timestamptz
	LastAutovacuum      pgtype.Timestamptz
	LastAnalyze         pgtype.Timestamptz
	LastAutoanalyze     pgtype.Timestamptz
	ColumnCount         int32
	HasPrimaryKey       bool
	CollectedAt         pgtype.Timestamptz
	StatsReset          pgtype.Timestamptz
	RelationClass       pgtype.Text
	IsPartition         bool
	ParentSchemaName    pgtype.Text
	ParentTableName     pgtype.Text
	PartitionBound      pgtype.Text
	TablespaceName      pgtype.Text
	Relpersistence      pgtype.Text
	Relrowsecurity      pgtype.Bool
	Relforcerowsecurity pgtype.Bool
	TableComment        pgtype.Text
	StorageParameters   []string
}

type TimescaleVersionSnapshot struct {
	ID                pgtype.UUID
	AuditRunID        pgtype.UUID
	EnvironmentID     pgtype.UUID
	DatabaseName      string
	ExtensionName     string
	ExtensionVersion  string
	SchemaName        pgtype.Text
	Major             int32
	Minor             int32
	Patch             int32
	Compatible        bool
	CompatibilityNote pgtype.Text
	CollectionStatus  string
	CollectedAt       pgtype.Timestamptz
}

type TriggerSnapshot struct {
	ID                pgtype.UUID
	AuditRunID        pgtype.UUID
	EnvironmentID     pgtype.UUID
	DatabaseName      string
	SchemaName        string
	TableName         string
	TriggerName       string
	Enabled           pgtype.Text
	Timing            pgtype.Text
	EventManipulation pgtype.Text
	ActionStatement   pgtype.Text
	CollectedAt       pgtype.Timestamptz
}

type ViewSnapshot struct {
	ID              pgtype.UUID
	AuditRunID      pgtype.UUID
	EnvironmentID   pgtype.UUID
	DatabaseName    string
	SchemaName      string
	ViewName        string
	OwnerName       pgtype.Text
	Relkind         string
	ViewDefinition  string
	SizeBytes       int64
	CollectedAt     pgtype.Timestamptz
	ColumnsJson     []byte
	SecurityInvoker pgtype.Bool
	SecurityBarrier pgtype.Bool
	IsPopulated     pgtype.Bool
}

type WorkloadSnapshot struct {
	ID                pgtype.UUID
	AuditRunID        pgtype.UUID
	EnvironmentID     pgtype.UUID
	DatabaseName      string
	QueryFingerprint  string
	QueryID           string
	Calls             int64
	TotalExecTimeMs   float64
	MeanExecTimeMs    float64
	RowsTotal         int64
	SharedBlocksRead  int64
	SharedBlocksHit   int64
	ReferencedObjects []string
	StatsReset        pgtype.Timestamptz
	Source            string
	EvidenceQuality   string
	ExtensionVersion  string
	QueryKind         string
	CollectedAt       pgtype.Timestamptz
}
